task: '10_narrative_recall'
#hf_cache_dir: '/srv/data/egasj/hf_cache/'
hf_cache_dir: '/home/user/Documents/hf_cache/'
#hf_cache_dir: '/media/jvel/data/hf_cache/'

pretrained_model_details:
#  checkpoint_path: '/srv/data/egasj/code/wav2vec2_patho/wav2vec2-large-xlsr-beaBase-20percent/checkpoint-51800'
#  checkpoint_path: '/home/user/Documents/data/bea16k_hungarian/bea16k_3.0_hungarian/checkpoint-3390'
#  checkpoint_path: '/home/user/Documents/data/bea16k_hungarian/bea16k_5.0_hungarian/checkpoint-5650'
#  checkpoint_path: 'jonatasgrosman/wav2vec2-large-xlsr-53-hungarian'

#  checkpoint_path: 'jonatasgrosman/wav2vec2-large-xlsr-53-hungarian'
#  checkpoint_path: 'facebook/wav2vec2-base-960h'
#  checkpoint_path: 'facebook/wav2vec2-large-960h'
#  checkpoint_path: 'facebook/wav2vec2-large-xlsr-53'
#  checkpoint_path: 'jonatasgrosman/wav2vec2-large-xlsr-53-english'
#  checkpoint_path: 'facebook/wav2vec2-xls-r-300m'
#  checkpoint_path: 'facebook/wav2vec2-xls-r-1b'
  checkpoint_path: 'facebook/data2vec-audio-base-960h'
paths:
  to_labels: 'data/10_narrative_recall/labels_maci.csv'
#  to_labels: 'data/10_narrative_recall/labels.csv' # jvel PC
  to_save_metadata: 'data/10_narrative_recall/'
#  audio_path: '/srv/data/egasj/corpora/SM/10_narrative_recall/'
  audio_path: '/home/user/Documents/corpora/SM/10_narrative_recall/'
#  audio_path: '/media/jvel/data/audio/SM/10_narrative_recall/'
  out_embeddings: 'data/10_narrative_recall/embeddings/'
  output_results: 'data/10_narrative_recall/results/sm_experiments.csv'

sampling_rate: 16000
# This is read from ../sclerosis_multiple.py
discrimination:
  emb_type: 'hiddens'
#  emb_type: 'convs'
shuffle_data: True
